--- #YAML:1.0
name:               TeX-Hyphen-Pattern
version:            0.04
abstract:           class for providing a collection of TeX hyphenation
author:
    - Roland van Ipenburg <ipenburg@xs4all.nl>
license:            perl
distribution_type:  module
configure_requires:
    ExtUtils::MakeMaker:  0
build_requires:
    ExtUtils::MakeMaker:  0
requires:
    Class::Meta::Express:  0
    Encode:               0
    File::Temp:           0
    Log::Log4perl:        0
    Module::Pluggable:    0
    Readonly:             0
    Set::Scalar:          0
    Test::More:           0.81
    Test::NoWarnings:     0
    version:              0
no_index:
    directory:
        - t
        - inc
generated_by:       ExtUtils::MakeMaker version 6.54
meta-spec:
    url:      http://module-build.sourceforge.net/META-spec-v1.4.html
    version:  1.4
